### ISSUE TITLE
Domain name

### ISSUE THREAD

**Issue by ahmadbkevin** [Jo0001/ViaSetup#12]
Hello, I simply wanted to raise this issue since I didn't want to remember the URL for viasetup, I want to contribute to this project by donating domain since it will be easier for folks to remember the url.
Please lemme know if you want it or not.

**Comment by Jo0001** [comment]
Hi
I think <my beautiful name>.github.io/<name of your loved tool> is not that hard to remember. 
Jokes aside, thanks for the offer but already have the viaversion.com domain. You can use https://viaversion.com/setup as easy to remember url.
